# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  exclude:
    labels: [github-actions, pre-commit, pep621]
  categories:
    - title: Changes
      labels: ["*"]
      exclude:
        labels: [dependencies]
    - title: Dependencies
      labels: [dependencies]
