name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  schedule:
    - cron: "25 7 */9 * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["310", "311", "312", "313", "314", "314t"]
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: boidolr/actions/run-tox@03ae71c93655c058abd43dd9bf3d44d670985fb6 # main
        with:
          python-version: ${{ matrix.python-version }}

  precommit:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: boidolr/actions/run-precommit@03ae71c93655c058abd43dd9bf3d44d670985fb6 # main
        env:
          UV_PYTHON: "3.14"
