name: Publish release
on:
  push:
    tags: ["v**"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.actor == 'boidolr'

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Create release for tag
        run: |
          TAG=$(echo "${{ github.ref }}" | cut -c 11-)
          gh release create --verify-tag --generate-notes "$TAG"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
