name: Publish release
on: create

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      github.actor == 'boidolr'

    steps:
      - name: Create release for tag
        uses: boidolr/actions/create-release@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          tag-name: "${{ github.ref }}"
